// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";
// Load .env from server folder
dotenv.config({ path: path.resolve(__dirname, "server/.env") });

export default defineConfig({
  schema: "server/prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    directUrl: process.env["DIRECT_URL"],
  },
});
